name: Notify subscribers

on:
  workflow_dispatch:
    inputs:
      slug:
        description: Post slug to send
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Call https://www.bertyl.com/blog/{slug}/notify
        env:
          NOTIFY_URL: https://www.bertyl.com/blog/${{ inputs.slug }}/notify
          NOTIFY_API_SECRET: ${{ secrets.NOTIFY_API_SECRET }}
        run: |
          curl \
            --fail-with-body \
            --show-error \
            --silent \
            -X POST \
            -H "Authorization: Bearer ${NOTIFY_API_SECRET}" \
            -H "Origin: https://www.bertyl.com" \
            "${NOTIFY_URL}"
